collections_config:
  pages:
    path: '.'
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    filter:
      base: strict
      exclude:
        - feed.njk
    _enabled_editors:
      - visual
  sites:
    path: sites
    disable_add_folder: true
    icon: link
    preview:
      gallery:
        text: " "
    schemas:
      default:
        path: src/_schemas/site.md
    _enabled_editors:
      - data
_inputs:
  date:
    type: date
    label: Published on
    comment: The blog post or site was published on this day.
  layout:
    hidden: true

